### ISSUE TITLE
Meta: Dev/test environment speedups

### ISSUE THREAD

**Issue by jherland** [tweag/FawltyDeps#423]
Making use of newer and faster tools to speed up our test runs and improve the developer experience:
- `ruff` to replace `pylint` and `black`.
- `uv` to replace `pip`.

### Tasks
- [x] Introduce `ruff` (PR #424)
- [x] Configure `ruff` to replace `pylint` (PR #425)
- [x] Remove `pylint` (PR #426)
- [x] Simplify `lint` pipeline to only run once (instead of once per Python version) (added to PR #426)
- [x] Configure `ruff` to replace `black` (PR #427)
- [x] Remove `black` (PR #427)
- [x] Introduce `uv` (added via `nox[uv]` in PR #432)
- [x] Use `uv` instead of `pip` where applicable (PR #432):
  - [x] in Nox sessions
  - [x] wherever we invoke `pip` our test suite
  - [x] use `uv` with fallback to `pip` in our `install_deps` logic.
